import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.keyword.HTMLTableComparator_RowValues_Test

runWithJUnitRunner(HTMLTableComparator_RowValues_Test.class)

