import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.keyword.HTMLTableComparator_Record_Test

runWithJUnitRunner(HTMLTableComparator_Record_Test.class)

