import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.keyword.HTMLTableComparator_RowKey_Test

runWithJUnitRunner(HTMLTableComparator_RowKey_Test.class)

